import expect from "expect";
import configureMockStore from "redux-mock-store";
import thunk from "redux-thunk";
import { backendUrl } from "../../util/backendUrl";
import { CardsActionsTypes } from "./CardsActionsTypes";
import * as actions from "./createCardActions";
import { Card } from "./types";

const middlewares = [thunk];
const mockStore = configureMockStore(middlewares);

describe("async create card action", () => {
  beforeEach(() => {
    fetchMock.resetMocks();
  });

  it("should BEGIN, fetch and SUCCESS on create card", () => {
    const store = mockStore();
    const card: Card = {
      _id: "id-autogenerated-in-backend",
      content: "Do the laundry",
      id: "card-13"
    };
    fetchMock.once(JSON.stringify(card));

    return store.dispatch(actions.createCard(card) as any).then(expectations());

    function expectations(): any {
      return () => {
        const expectedActions: CardsActionsTypes[] = [
          { type: actions.CREATE_CARD_BEGIN, payload: card },
          {
            payload: {
              ...card,
              _id: "id-autogenerated-in-backend",
              loading: false
            },
            type: actions.CREATE_CARD_SUCCESS
          }
        ];
        expect(store.getActions()).toEqual(expectedActions);
        expect(fetchMock.mock.calls.length).toEqual(1);
        expect(fetchMock.mock.calls[0][0].url).toEqual(backendUrl() + "/cards");
      };
    }
  });

  it("should BEGIN, fetch and FAILURE on create card that fails", () => {
    const error = new TypeError("Failed to fetch (simulated network error)");
    fetchMock.mockReject(error);
    const store = mockStore();
    const card: Card = { id: "card-13", content: "Do the laundry" };

    return store.dispatch(actions.createCard(card) as any).then(expectations());

    function expectations(): any {
      return () => {
        const expectedActions = [
          { type: actions.CREATE_CARD_BEGIN, payload: card },
          { type: actions.CREATE_CARD_FAILURE, payload: card, error }
        ];
        expect(store.getActions()).toEqual(expectedActions);
        expect(fetchMock.mock.calls.length).toEqual(1);
        expect(fetchMock.mock.calls[0][0].url).toEqual(backendUrl() + "/cards");
      };
    }
  });
});
